# coding=utf-8
# 选择器不可以#出现在首位会识别成注释
# 如果只存在id可以使用`*#id`或者`标签名#id`
name: default
url: https://pan-onemue.oss-cn-beijing.aliyuncs.com/pan_onemue_cn%2Fuser%2F1%2FBIj96ezr_demo.yml?Expires=1654763598
author: onemue
version: v 0.0.0
update-time: 2019-01-01
rules: 
    - url: ^.*[blog\.csdn\.net].*$
      rules:
        .toolbar-advert: display:none
    - url: ^.*//blog.csdn.net/.*/article/details/[0-9]*.*$
      rules: 
        .hide-article-box.hide-article-pos.text-center: display:none|height:auto
        .article_content.clearfix#article_content: height:auto
    - url: ^.*//.*.blog.csdn.net/article/details/[0-9]*.*$
      rules: 
        .hide-article-box.hide-article-pos.text-center: display:none|height:auto
        .article_content.clearfix#article_content: height:auto
    - url: ^.*\/\/www\.it1352\.com.*\.html$
      rules: 
        div.arc-body-main-more: display:none
        div.arc-body-main: height:auto
    - url: ^.*\/\/www\.shouhuola\.com.*\.html$
      rules:
        div.show-content.shortquestioncontent: display:none
        div.show-content.hidequestioncontent: display:block
    - url: ^.*\/\/www\.360doc\.com.*$
      rules:
        body.articleMaxH: ~.articleMaxH
    - url: ^.*/\/\ruanyifeng\.com.*$
      rules:
        [style="display:inline-block ! important;width:100%;"]: display:none
